SET SERVEROUTPUT ON;

CREATE OR REPLACE FUNCTION GET_DAY_NAME(P_DATE DATE)
RETURN VARCHAR2 
IS
BEGIN
    RETURN TO_CHAR(P_DATE, 'DAY');
END;
/
-- to execute a function, we must use anonymous blocks or select queries.
SELECT GET_DAY_NAME(TO_DATE('10-12-2020', 'MM-DD-YYYY')) FROM DUAL;

BEGIN
    DBMS_OUTPUT.PUT_LINE(GET_DAY_NAME(TO_DATE('10-12-2020', 'MM-DD-YYYY')));
END;
/